name: Tag and Release

on:
  push:
    branches:
      - main  # Replace with the name of your main branch

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "kdahal"
        git config --global user.email "kumar.dahal@outlook.com"

    - name: Create Git tag
      run: |
        # Generate a unique tag based on the current date and commit hash.
        TAG="v$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
        git tag "$v1.0.0"

    - name: Push Git tag
      run: |
        git push origin "$TAG"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
        tag_name: ${{ steps.create_tag.outputs.tag_name }}
        release_name: Release ${{ steps.create_tag.outputs.tag_name }}
        draft: false
        prerelease: false

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
